spring:
  profiles:
    active:
      - prod
  datasource:
    url: jdbc:postgresql://ec2-35-168-65-132.compute-1.amazonaws.com:5432/d45i08ccifd54q
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistence:
          validation:
            mode: none
            show-sql: false
    show-sql: true
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://ec2-35-168-65-132.compute-1.amazonaws.com:5432/d45i08ccifd54q
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
syftgolf:
  upload-path: uploads-prod
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
syftgolf:
  upload-path: uploads-dev

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://localhost:5432/syftgolf
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop

syftgolf:
  upload-path: uploads-test







#spring:
#  profiles:
#    active:
#      - test
#  datasource:
#    url: jdbc:postgresql://localhost:5432/testdb
#    username: postgres
#    password: admin
#  jpa:
#
#
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#
#      javax:
#        persistence:
#          validation:
#            mode: none
#    show-sql: false
#  data:
#    web:
#      pageable:
#        default-page-size: 10
#        max-page-size: 100
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
#---
#spring:
#  config:
#    activate:
#      on-profile: prod
#  datasource:
#    url: jdbc:postgresql://localhost:5432/proddb
#    username: postgres
#    password: admin
#  jpa:
#    hibernate:
#      ddl-auto: update
#syftgolf:
#  upload-path: uploads-prod
#
#---
#spring:
#  config:
#    activate:
#      on-profile: dev
#  datasource:
#    url: jdbc:postgresql://localhost:5432/devdb
#    username: postgres
#    password: admin
#  jpa:
#    hibernate:
#      ddl-auto: update
#syftgolf:
#  upload-path: uploads-dev
#
#---
#spring:
#  config:
#    activate:
#      on-profile: test
#  datasource:
#    url: jdbc:postgresql://localhost:5432/testdb
#    username: postgres
#    password: admin
#  jpa:
#    hibernate:
#      ddl-auto: update
#
#syftgolf:
#  upload-path: uploads-test
