spring:
  profiles:
    active:
      - prod
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: admin
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
      show-sql: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show-sql: true
      javax:
        persistence:
          validation:
            mode: none
    show-sql: true
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100

---
spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
syftgolf:
  upload-path: uploads-prod
---
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: admin
    jpa:
      hibernate:
        ddl-auto: update
syftgolf:
  upload-path: uploads-prod

---
spring:
  profiles: test
  datasource:
    url: jdbc:postgresql://localhost:5432/syftgolf
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop

syftgolf:
  upload-path: uploads-test





